name: fetch-repository-stats
concurrency: fetch-repository-stats

on:
  schedule:
    - cron: "0 23 * * *" # 11:00 pm
  workflow_dispatch:

jobs:
  run-ghrs-with-matrix:
    name: github-ventus-repo-stats
    runs-on: ubuntu-latest
    strategy:
      matrix:
        statsRepo: ['Jules-Kong/OpenCL-CTS', 'Jules-Kong/ventus_cpu_guide']
      fail-fast: false
      max-parallel: 1
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          ghpagesprefix: https://Jules-Kong.github.io/action-repo-stat-record
          repository: ${{ matrix.statsRepo }}
          ghtoken: ${{ secrets.ghrs_github_api_token }}
